[RO-45] Added context as alias and made publicPath relative.
oat-sa/portal-core-fe pull request #15
Opened 2020-12-24 10:21 UTC by vanya6537

Ticket: https://oat-sa.atlassian.net/browse/RO-45

Absolute paths in generated bundle were fixed.

### Changed:
- Context as alias
- publicPath relative

2020-12-28 08:33 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-12-28 08:50 UTC, bziondik requested changes
Please, add bump version
After release (you can use taoRelease tool https://github.com/oat-sa/tao-extension-release) create PR for https://github.com/oat-sa/test-taker-portal with new version

2020-12-29 08:24 UTC, bziondik approved these changes

2020-12-29 09:08 UTC, ioweh approved these changes

2020-12-29 10:38 UTC, merged